"""Initial schema

Revision ID: 22865fffcd99
Revises: 
Create Date: 2026-03-26 03:41:12.768058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22865fffcd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.Column('dados_bancarios', sa.JSON(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'FINANCEIRO', 'PRODUCAO', 'VISUALIZACAO', name='userrole'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=2), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status_negociacao', sa.Enum('LEAD', 'CONTATO', 'PROPOSTA', 'NEGOCIACAO', 'FECHADO', 'PERDIDO', name='negociacaostatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=False)
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_table('usuario_empresa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('permissoes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_empresa_empresa_id'), 'usuario_empresa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_empresa_usuario_id'), 'usuario_empresa', ['usuario_id'], unique=False)
    op.create_table('historico_clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_clientes_cliente_id'), 'historico_clientes', ['cliente_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'ENVIADO', 'APROVADO', 'REJEITADO', name='orcamentostatus'), nullable=True),
    sa.Column('validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condicoes_pagamento', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('total_custo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_venda', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_lucro', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('link_compartilhamento', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_compartilhamento')
    )
    op.create_index(op.f('ix_orcamentos_cliente_id'), 'orcamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_empresa_id'), 'orcamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_numero'), 'orcamentos', ['numero'], unique=False)
    op.create_index(op.f('ix_orcamentos_status'), 'orcamentos', ['status'], unique=False)
    op.create_table('itens_orcamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('venda_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('venda_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lucro', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_orcamento_orcamento_id'), 'itens_orcamento', ['orcamento_id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'EM_ANDAMENTO', 'REVISAO', 'CONCLUIDO', 'CANCELADO', name='projectstatus'), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_prevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_cliente_id'), 'projetos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_projetos_empresa_id'), 'projetos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_projetos_status'), 'projetos', ['status'], unique=False)
    op.create_table('colunas_kanban',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colunas_kanban_projeto_id'), 'colunas_kanban', ['projeto_id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('projeto_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('PAGAR', 'RECEBER', name='contatipo'), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', name='contastatus'), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('comprovante_url', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_data_vencimento'), 'contas', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_empresa_id'), 'contas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_contas_projeto_id'), 'contas', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_contas_status'), 'contas', ['status'], unique=False)
    op.create_index(op.f('ix_contas_tipo'), 'contas', ['tipo'], unique=False)
    op.create_table('tarefas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coluna_id', sa.String(length=36), nullable=True),
    sa.Column('responsavel_id', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('prazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('anexos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coluna_id'], ['colunas_kanban.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_coluna_id'), 'tarefas', ['coluna_id'], unique=False)
    op.create_index(op.f('ix_tarefas_responsavel_id'), 'tarefas', ['responsavel_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tarefa_id', sa.String(length=36), nullable=True),
    sa.Column('autor_id', sa.String(length=36), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_autor_id'), 'comentarios', ['autor_id'], unique=False)
    op.create_index(op.f('ix_comentarios_tarefa_id'), 'comentarios', ['tarefa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comentarios_tarefa_id'), table_name='comentarios')
    op.drop_index(op.f('ix_comentarios_autor_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_tarefas_responsavel_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_coluna_id'), table_name='tarefas')
    op.drop_table('tarefas')
    op.drop_index(op.f('ix_contas_tipo'), table_name='contas')
    op.drop_index(op.f('ix_contas_status'), table_name='contas')
    op.drop_index(op.f('ix_contas_projeto_id'), table_name='contas')
    op.drop_index(op.f('ix_contas_empresa_id'), table_name='contas')
    op.drop_index(op.f('ix_contas_data_vencimento'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_colunas_kanban_projeto_id'), table_name='colunas_kanban')
    op.drop_table('colunas_kanban')
    op.drop_index(op.f('ix_projetos_status'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_empresa_id'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_cliente_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_itens_orcamento_orcamento_id'), table_name='itens_orcamento')
    op.drop_table('itens_orcamento')
    op.drop_index(op.f('ix_orcamentos_status'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_numero'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_empresa_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_cliente_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_historico_clientes_cliente_id'), table_name='historico_clientes')
    op.drop_table('historico_clientes')
    op.drop_index(op.f('ix_usuario_empresa_usuario_id'), table_name='usuario_empresa')
    op.drop_index(op.f('ix_usuario_empresa_empresa_id'), table_name='usuario_empresa')
    op.drop_table('usuario_empresa')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
